# This is jenkins auto build

name: jenkins-action
on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]
   # if: github.event.pull_request.merged == true

jobs:
  jenkins_build:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: start build jenkins
        run : echo "hello World"

