# This is jenkins auto build

name: jenkins-action
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  jenkins_build:
 ##   if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: start build jenkins
        run : curl https://yaroslav_gorohov:${{ secrets.JENKINS_TOKEN2 }}@buildserver.onlyoffice.com/job/test_build2build?token=qwSSDFWD12SDFD34dfGDSRRGRDX67zed
